server:
  port: 7001
#security:
#  user:
#    name: root
#    password: 123456
#  basic:
#    enabled: true
eureka:
  instance:
    hostname: eureka7001.com      #eureka服务端的实例名称
  client:
    register-with-eureka: false   #false  表示不向注册中心注册自己
    fetch-registry: false         #false  表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/


