server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件所在的路径
  type-aliases-package: com.ys.entities               #所有Entities别名在所在的包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                 #mapper 映射文件
spring:
  application:
    name: microservicecloud-bms
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://172.16.90.155:3306/CAFETERIA?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: CAFETERIA
    password: tinno@2017
    dbcp2:
          min-idle: 5                                           # 数据库连接池的最小维持连接数
          initial-size: 5                                       # 初始化连接数
          max-total: 5                                          # 最大连接数
          max-wait-millis: 200                                  # 等待连接获取的最大超时时间
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

  instance:
    instance-id: microservicecloud-bms8001
    prefer-ip-address: true


info:
  app.name: ys-microservicecloud
  company.name: www.ys.com
  build.artifactId: serviceOrder-provider-dept-8001
  build.version: 1.0-SNAPSHOT
logging:
  level:
    com.ys.dao: debug


